const functionTestCases = [
  {
    description: "初始化具名函式",
    source: "function test(){};",
    expect: [
      { type: "keyword", value: "function" },
      { type: "identifier", value: "test" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化具名函式有參數",
    source: "function test(a, b, c, 123, 'str'){};",
    expect: [
      { type: "keyword", value: "function" },
      { type: "identifier", value: "test" },
      { type: "punctuation", value: "(" },
      { type: "identifier", value: "a" },
      { type: "punctuation", value: "," },
      { type: "identifier", value: "b" },
      { type: "punctuation", value: "," },
      { type: "identifier", value: "c" },
      { type: "punctuation", value: "," },
      { type: "number", value: "123" },
      { type: "punctuation", value: "," },
      { type: "string", value: "str" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化具名函式有參數 v2",
    source: "function test([], [1,2,3], {}, { key1: 'value1' }){};",
    expect: [
      { type: "keyword", value: "function" },
      { type: "identifier", value: "test" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: "[" },
      { type: "punctuation", value: "]" },
      { type: "punctuation", value: "," },
      { type: "punctuation", value: "[" },
      { type: "number", value: "1" },
      { type: "punctuation", value: "," },
      { type: "number", value: "2" },
      { type: "punctuation", value: "," },
      { type: "number", value: "3" },
      { type: "punctuation", value: "]" },
      { type: "punctuation", value: "," },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: "," },
      { type: "punctuation", value: "{" },
      { type: "identifier", value: "key1" },
      { type: "punctuation", value: ":" },
      { type: "string", value: "value1" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化函式存在變數中",
    source: "const test = function (){};",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "keyword", value: "function" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化函式存在變數中",
    source: "const test = function ([], [1,2,3], {}, { key1: 'value1' }){};",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "keyword", value: "function" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: "[" },
      { type: "punctuation", value: "]" },
      { type: "punctuation", value: "," },
      { type: "punctuation", value: "[" },
      { type: "number", value: "1" },
      { type: "punctuation", value: "," },
      { type: "number", value: "2" },
      { type: "punctuation", value: "," },
      { type: "number", value: "3" },
      { type: "punctuation", value: "]" },
      { type: "punctuation", value: "," },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: "," },
      { type: "punctuation", value: "{" },
      { type: "identifier", value: "key1" },
      { type: "punctuation", value: ":" },
      { type: "string", value: "value1" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化非同步函式",
    source: "const test = async function (){};",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "keyword", value: "async" },
      { type: "keyword", value: "function" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化非同步函式 v2",
    source: "const test = async function () { await test2() };",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "keyword", value: "async" },
      { type: "keyword", value: "function" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "keyword", value: "await" },
      { type: "identifier", value: "test2" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化同步函式有返回字串",
    source: "const test = function () { return '1324' };",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "keyword", value: "function" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "keyword", value: "return" },
      { type: "string", value: "1324" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化同步函式有返回值數字",
    source: "const test = function () { return 1324 };",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "keyword", value: "function" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "keyword", value: "return" },
      { type: "number", value: "1324" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化同步函式有返回值陣列",
    source: "const test = function () { return [1,2,3] };",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "keyword", value: "function" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "keyword", value: "return" },
      { type: "punctuation", value: "[" },
      { type: "number", value: "1" },
      { type: "punctuation", value: "," },
      { type: "number", value: "2" },
      { type: "punctuation", value: "," },
      { type: "number", value: "3" },
      { type: "punctuation", value: "]" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化同步函式有返回值物件",
    source: "const test = function () { return { key1: 'value1' } };",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "keyword", value: "function" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "punctuation", value: "{" },
      { type: "keyword", value: "return" },
      { type: "punctuation", value: "{" },
      { type: "identifier", value: "key1" },
      { type: "punctuation", value: ":" },
      { type: "string", value: "value1" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "箭頭函式",
    source: "const test = () => { return { key1: 'value1' } };",
    expect: [
      { type: "keyword", value: "const" },
      { type: "identifier", value: "test" },
      { type: "operator", value: "=" },
      { type: "punctuation", value: "(" },
      { type: "punctuation", value: ")" },
      { type: "operator", value: "=>" },
      { type: "punctuation", value: "{" },
      { type: "keyword", value: "return" },
      { type: "punctuation", value: "{" },
      { type: "identifier", value: "key1" },
      { type: "punctuation", value: ":" },
      { type: "string", value: "value1" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
];

export { functionTestCases };
