const objectTestCases = [
  {
    description: "初始化空物件",
    source: "let x = {};",
    expect: [
      { type: "keyword", value: "let" },
      { type: "identifier", value: "x" },
      { type: "operator", value: "=" },
      { type: "punctuation", value: "{" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化單一元素物件;",
    source: "let x = { key: value };",
    expect: [
      { type: "keyword", value: "let" },
      { type: "identifier", value: "x" },
      { type: "operator", value: "=" },
      { type: "punctuation", value: "{" },
      { type: "identifier", value: "key" },
      { type: "punctuation", value: ":" },
      { type: "identifier", value: "value" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化多元素物件",
    source: "let x = { key1: value1, key2: value2, key3: value3 };",
    expect: [
      { type: "keyword", value: "let" },
      { type: "identifier", value: "x" },
      { type: "operator", value: "=" },
      { type: "punctuation", value: "{" },
      { type: "identifier", value: "key1" },
      { type: "punctuation", value: ":" },
      { type: "identifier", value: "value1" },
      { type: "punctuation", value: "," },
      { type: "identifier", value: "key2" },
      { type: "punctuation", value: ":" },
      { type: "identifier", value: "value2" },
      { type: "punctuation", value: "," },
      { type: "identifier", value: "key3" },
      { type: "punctuation", value: ":" },
      { type: "identifier", value: "value3" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "初始化物件包其他資料型別, e.g. string, number, array, etc",
    source:
      'let x = { key1: "str", key2: 123, key3: [1,2,3], key4: { key1: "nestedObjStr" } };',
    expect: [
      { type: "keyword", value: "let" },
      { type: "identifier", value: "x" },
      { type: "operator", value: "=" },
      { type: "punctuation", value: "{" },
      { type: "identifier", value: "key1" },
      { type: "punctuation", value: ":" },
      { type: "string", value: "str" },
      { type: "punctuation", value: "," },
      { type: "identifier", value: "key2" },
      { type: "punctuation", value: ":" },
      { type: "number", value: "123" },
      { type: "punctuation", value: "," },
      { type: "identifier", value: "key3" },
      { type: "punctuation", value: ":" },
      { type: "punctuation", value: "[" },
      { type: "number", value: "1" },
      { type: "punctuation", value: "," },
      { type: "number", value: "2" },
      { type: "punctuation", value: "," },
      { type: "number", value: "3" },
      { type: "punctuation", value: "]" },
      { type: "punctuation", value: "," },
      { type: "identifier", value: "key4" },
      { type: "punctuation", value: ":" },
      { type: "punctuation", value: "{" },
      { type: "identifier", value: "key1" },
      { type: "punctuation", value: ":" },
      { type: "string", value: "nestedObjStr" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: "}" },
      { type: "punctuation", value: ";" },
    ],
  },
];

export { objectTestCases };
