const operatorTestCases = [
  {
    description: "賦值",
    source: "let x = 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "不嚴格相等",
    source: "let x = 5 == 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: "==" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "嚴格相等",
    source: "let x = 5 === 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: "===" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "大於",
    source: "let x = 5 > 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: ">" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "右移",
    source: "let x = 5 >> 1;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: ">>" },
      { type: "number", value: "1" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "無符號右移",
    source: "let x = 5 >>> 1;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: ">>>" },
      { type: "number", value: "1" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "大於等於",
    source: "let x = 5 >= 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: ">=" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "小於",
    source: "let x = 5 < 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: "<" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "左移",
    source: "let x = 5 << 1;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: "<<" },
      { type: "number", value: "1" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "無符號左移",
    source: "let x = 5 <<< 1;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: "<<<" },
      { type: "number", value: "1" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "小於等於",
    source: "let x = 5 <= 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: "<=" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "取反",
    source: "let x = !5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "operator", value: "!" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "不嚴格不等於",
    source: "let x = 5 != 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: "!=" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
  {
    description: "嚴格不等於",
    source: "let x = 5 !== 5;",
    expect: [
      { type: "keyword", value: "let" },
      { type: "name", value: "x" },
      { type: "operator", value: "=" },
      { type: "number", value: "5" },
      { type: "operator", value: "!==" },
      { type: "number", value: "5" },
      { type: "punctuation", value: ";" },
    ],
  },
];

export { operatorTestCases };
